### ISSUE TITLE
Improve UI!

### ISSUE THREAD

**Issue by jt-nti** [jt-nti/barnard-castle#4]

**Comment by andypiper** [comment]
- add icon and colours
- add manifest and meta tags for home screen installation and launch on mobile
- add help text / information about what this is for / does
- use a responsive stylesheet

**Comment by andypiper** [comment]
(I’ve made a fork to work on these)

**Comment by jt-nti** [comment]
Yay! If it helps, I had a kind of QR-code-ish-coronavirus icon in mind :)

**Comment by jt-nti** [comment]
Added the kind of icon I was thinking of in #10 but improvements most welcome! (It does still work as a QR code which is kind of nice :)

**Comment by andypiper** [comment]
I might just wait for you to do the remaining, then... :-P the icon is cool though.

**Comment by jt-nti** [comment]
How could you improve on the current world-beating UI anyway? :)

I'm just going to muck about with the icon some more...

**Comment by jt-nti** [comment]
Made a start in #16 
It is at least responsive now but still needs work, e.g. now it isn't great on bigger screens!

**Comment by andypiper** [comment]
Achievement unlocked!

**Comment by jt-nti** [comment]
I think this is mostly done now, although PRs are always welcome to improve the UI even more, for example for #29!
