### ISSUE TITLE
Check QR code is valid

### ISSUE THREAD

**Issue by jt-nti** [jt-nti/barnard-castle#6]
Possible to verify the JWT is signed by the NHS using their public key?

**Comment by andysc** [comment]
see `hasValidSignature()` [here](https://github.com/nhsx/covid-19-app-android-ag-public/blob/master/app/src/main/java/uk/nhs/nhsx/covid19/android/app/qrcode/QrCodeParser.kt)

And this might come in handy... ;)
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVyPX5CqxSdg0JE/2O0wog0qmvza/\nGLVAxNmJROQwMjtzk1U5YESBvk7njod0LJwVTmw+w/aIRvvnQsB1w5CW1g==
-----END PUBLIC KEY-----
```

**Comment by jt-nti** [comment]
Done as part of venue publish API
